pipeline {
  agent any

  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

   environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
      }
   stages {
        stage ("initial cleanup") {
            steps {
                dir("${WORKSPACE}") {
                deleteDir()
                }
                }
            }
        stage('Checkout SCM') {
            steps{
                git branch: 'feature/Jenkkins-pipeline', url: 'https://github.com/Ohiani/ansible-config.git'
                   }
            }
        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}' 
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
                }
            }

        stage('Run Ansible playbook') {
          steps {
              ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
                  }
            }
            
        
   
   
   
   
   
   
   
   
   }
}